/**
 * Generate GraphQL API documentation (#898).
 *
 *   npm run docs:graphql
 *
 * Writes docs/graphql/schema.graphql (printed SDL) and docs/graphql/README.md
 * (Markdown reference of every query, mutation and type, using the schema's
 * descriptions).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  GraphQLEnumType,
  GraphQLInputObjectType,
  GraphQLObjectType,
  GraphQLScalarType,
  printSchema,
  type GraphQLField,
} from "graphql";
import { schema } from "../src/graphql/typeDefs.js";
import { MAX_COMPLEXITY, MAX_DEPTH } from "../src/graphql/complexity.js";

const outDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../docs/graphql");
mkdirSync(outDir, { recursive: true });

writeFileSync(path.join(outDir, "schema.graphql"), printSchema(schema) + "\n");

const anchor = (name: string) => `#${name.toLowerCase()}`;
const typeLink = (t: string) => {
  const named = t.replace(/[[\]!]/g, "");
  const custom = schema.getType(named) && !named.startsWith("__") && !["String", "Int", "Float", "Boolean", "ID"].includes(named);
  return custom ? `[\`${t}\`](${anchor(named)})` : `\`${t}\``;
};

function fieldRow(f: GraphQLField<unknown, unknown>) {
  const args = f.args.length
    ? f.args.map((a) => `${a.name}: ${a.type}${a.defaultValue !== undefined ? ` = ${JSON.stringify(a.defaultValue)}` : ""}`).join(", ")
    : "";
  return `| \`${f.name}${args ? `(${args})` : ""}\` | ${typeLink(String(f.type))} | ${(f.description ?? "").replace(/\n/g, " ")} |`;
}

const lines: string[] = [
  "# SolarGrid GraphQL API",
  "",
  "<!-- Generated by `npm run docs:graphql` (backend/scripts/generate-graphql-docs.ts). Do not edit by hand. -->",
  "",
  "Endpoint: `POST /graphql` (also `/api/graphql`). Open `GET /graphql` in a browser for the playground.",
  "",
  `Limits: max depth **${MAX_DEPTH}**, max complexity **${MAX_COMPLEXITY}** (override with \`GRAPHQL_MAX_DEPTH\` / \`GRAPHQL_MAX_COMPLEXITY\`).`,
  "Each field costs 1; list fields multiply their children by `pageSize`/`limit`/`days` (default 10, max 100);",
  "fields that hit the chain or a third-party API add a surcharge. The computed cost is returned in `extensions.cost`.",
  "",
  "REST endpoints without a typed field are reachable via `rest(path:)` (GET) and `rest(method:, path:, body:)` (mutation),",
  "which forward your `Authorization` / `X-Admin-Key` / `X-API-Key` headers.",
  "",
];

for (const [title, root] of [
  ["Queries", schema.getQueryType()],
  ["Mutations", schema.getMutationType()],
  ["Subscriptions", schema.getSubscriptionType()],
] as const) {
  if (!root) continue;
  lines.push(`## ${title}`, "", "| Field | Returns | Description |", "| --- | --- | --- |");
  for (const f of Object.values(root.getFields())) lines.push(fieldRow(f));
  lines.push("");
}

lines.push("## Types", "");
const roots = new Set(["Query", "Mutation", "Subscription"]);
for (const type of Object.values(schema.getTypeMap()).sort((a, b) => a.name.localeCompare(b.name))) {
  if (type.name.startsWith("__") || roots.has(type.name)) continue;
  if (type instanceof GraphQLObjectType || type instanceof GraphQLInputObjectType) {
    lines.push(`### ${type.name}`, "");
    if (type.description) lines.push(type.description, "");
    lines.push("| Field | Type | Description |", "| --- | --- | --- |");
    for (const f of Object.values(type.getFields())) {
      lines.push("args" in f ? fieldRow(f as GraphQLField<unknown, unknown>) : `| \`${f.name}\` | ${typeLink(String(f.type))} | ${f.description ?? ""} |`);
    }
    lines.push("");
  } else if (type instanceof GraphQLEnumType) {
    lines.push(`### ${type.name}`, "", type.getValues().map((v) => `\`${v.name}\``).join(" · "), "");
  } else if (type instanceof GraphQLScalarType && !["String", "Int", "Float", "Boolean", "ID"].includes(type.name)) {
    lines.push(`### ${type.name}`, "", type.description ?? "Custom scalar.", "");
  }
}

writeFileSync(path.join(outDir, "README.md"), lines.join("\n"));
console.log(`GraphQL docs written to ${outDir}`);
